project:
  type: website

website:
  title: "Sungwoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: statistics.qmd
        text: Statistics
      - href: project.qmd
        text: Project
      - href: note.qmd
        text: Note
      - href: about.qmd
        text: About
        
format:
  html:
    theme: minty
    css: styles.css
    toc: true



