project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Main
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



